### ISSUE TITLE
Keep all dependencies in one folder in root

### ISSUE THREAD

**Issue by lewisknewton** [portsoc/iArsenic#21]
Currently, there are multiple node_modules folders throughout the project.

**Comment by jacekkopecky** [comment]
Move geodata into preprocessing, that's all consolidation that naturally wants to be done.

But also please propose where lib/geo-data.js should live after that.

**Comment by lewisknewton** [comment]
Everything complete except new location of lib/geo-data.js, as model5-preprocessor.js uses this.

**Comment by jacekkopecky** [comment]
I just noticed that server lost its package.json in 0ea157ec5aac1d747f225ccf4ec65d694ac2d1bc but it shouldn't – that package.json is necessary when we want to deploy this as a cloud function, isn't it?

**Comment by lewisknewton** [comment]
Package files for `server` added in commit 28bfeb2bab3b9f53c31907e192defcc7e9192fe9.

**Comment by TxJson** [comment]
This issue was resolved a long while ago (2418b8e). Closing issue.
